apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: voting-app
spec:
  containers:
    - name: db-container
      image: postgres:9.4
      env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
      ports:
        - containerPort: 5432